In [18]:
import pandas as pd
import numpy as np
import math 


l = np.array([[2, -2], [5, 6], [-4, -4], [-7, 1], [8, 14]])
ys = np.array([])

m=len(l)

dif = 0
dif2 = 0



In [19]:
m


5

In [20]:
for i in ls:
    x = i[0]
    z = i[1]
    y = 1.2 * x + 2
    
    dif = dif + abs(y-z)
    
    
    

In [21]:
result = dif/m

In [22]:
result

3.88

In [23]:
for i in ls:
    x = i[0]
    z = i[1]
    y = 1.2 * x + 2
    
    dif2 = dif2 + (y-z)**2
    

In [24]:
result2 = dif2/(2*m)

In [25]:
result2

10.692000000000002

### Linear_regression


In [133]:
import numpy.matlib 
import numpy as np 


In [134]:
data = np.loadtxt('lin_reg_dat.txt', delimiter = ',')


In [135]:
(data[0])

array([-0.72407,  2.23863])

In [136]:
X = data[:,:-1]
y = data[:,-1]

In [210]:
X.shape, y.shape

((100, 1), (100,))

In [137]:
X[0]

array([-0.72407])

In [138]:
X.shape[1]

1

In [164]:
y

array([ 2.23863e+00, -1.56000e-03,  3.01665e+00,  2.31019e+00,
        2.05950e+00,  1.24736e+00,  2.82497e+00,  2.21802e+00,
        1.43644e+00,  1.74980e+00,  1.63259e+00,  2.43461e+00,
        1.02226e+00,  3.11769e+00,  8.11940e-01,  2.81910e+00,
        5.31050e-01,  1.64845e+00,  1.91416e+00,  2.11376e+00,
        1.70969e+00,  2.92253e+00,  3.29827e+00,  1.58565e+00,
        2.30455e+00,  1.79169e+00,  1.54723e+00,  1.06893e+00,
        1.78802e+00,  1.84746e+00,  1.58732e+00,  1.94799e+00,
        3.09324e+00,  1.86155e+00,  1.88817e+00,  1.39474e+00,
        1.71526e+00,  1.75695e+00,  1.12981e+00,  1.67000e+00,
        6.67110e-01,  3.11987e+00,  5.69240e-01,  2.28231e+00,
        1.23798e+00,  1.35803e+00,  1.75579e+00,  1.91470e+00,
        2.33029e+00,  3.25263e+00,  2.07602e+00,  1.54254e+00,
        2.79202e+00,  1.96178e+00,  9.58980e-01,  1.96690e+00,
        3.06144e+00,  1.85984e+00,  1.82967e+00,  6.22850e-01,
        3.63838e+00,  1.11807e+00,  2.91735e+00,  1.996

In [140]:
Xn_points = X.shape[0]
W = np.zeros(X.shape[1])
b=0

In [141]:
Xn_points

100

In [167]:
W

array([0.5])

In [168]:
W[0]=.5

In [169]:
W

array([0.5])

In [208]:
X

array([[-7.24070e-01],
       [-2.40724e+00],
       [ 2.64837e+00],
       [ 3.60920e-01],
       [ 6.73120e-01],
       [-4.54600e-01],
       [ 2.20168e+00],
       [ 1.15605e+00],
       [ 5.06940e-01],
       [-8.59520e-01],
       [-5.99700e-01],
       [ 1.46804e+00],
       [-1.05659e+00],
       [ 1.29177e+00],
       [-7.45650e-01],
       [ 1.50330e-01],
       [-1.49627e+00],
       [-7.20710e-01],
       [ 3.29240e-01],
       [-2.80530e-01],
       [-1.36115e+00],
       [ 7.46780e-01],
       [ 1.06210e-01],
       [ 3.25600e-02],
       [-9.82900e-01],
       [-1.15661e+00],
       [ 9.02400e-02],
       [-1.03816e+00],
       [-6.04000e-03],
       [ 1.62780e-01],
       [-6.98690e-01],
       [ 1.03857e+00],
       [-1.17830e-01],
       [-9.54090e-01],
       [-8.18390e-01],
       [-1.28802e+00],
       [ 6.28220e-01],
       [-2.29674e+00],
       [-8.56010e-01],
       [-1.75223e+00],
       [-1.19662e+00],
       [ 9.77810e-01],
       [-1.17110e+00],
       [ 1.

In [165]:
y_pred = np.matmul(X, W) #+ b


In [166]:
y_pred

array([-3.620350e-01, -1.203620e+00,  1.324185e+00,  1.804600e-01,
        3.365600e-01, -2.273000e-01,  1.100840e+00,  5.780250e-01,
        2.534700e-01, -4.297600e-01, -2.998500e-01,  7.340200e-01,
       -5.282950e-01,  6.458850e-01, -3.728250e-01,  7.516500e-02,
       -7.481350e-01, -3.603550e-01,  1.646200e-01, -1.402650e-01,
       -6.805750e-01,  3.733900e-01,  5.310500e-02,  1.628000e-02,
       -4.914500e-01, -5.783050e-01,  4.512000e-02, -5.190800e-01,
       -3.020000e-03,  8.139000e-02, -3.493450e-01,  5.192850e-01,
       -5.891500e-02, -4.770450e-01, -4.091950e-01, -6.440100e-01,
        3.141100e-01, -1.148370e+00, -4.280050e-01, -8.761150e-01,
       -5.983100e-01,  4.889050e-01, -5.855500e-01,  7.917500e-02,
       -2.945900e-01, -8.983900e-01, -4.786350e-01,  3.227800e-01,
        1.231250e-01,  2.295850e-01,  6.051800e-01, -3.005800e-01,
        1.342550e-01,  2.479700e-01, -1.339385e+00,  2.470100e-01,
        5.932150e-01, -8.870500e-02,  2.896900e-01, -1.074630e

In [162]:
error = y - y_pred


In [163]:
error

array([2.600665, 1.20206 , 1.692465, 2.12973 , 1.72294 , 1.47466 ,
       1.72413 , 1.639995, 1.18297 , 2.17956 , 1.93244 , 1.70059 ,
       1.550555, 2.471805, 1.184765, 2.743935, 1.279185, 2.008805,
       1.74954 , 2.254025, 2.390265, 2.54914 , 3.245165, 1.56937 ,
       2.796   , 2.369995, 1.50211 , 1.58801 , 1.79104 , 1.76607 ,
       1.936665, 1.428705, 3.152155, 2.338595, 2.297365, 2.03875 ,
       1.40115 , 2.90532 , 1.557815, 2.546115, 1.26542 , 2.630965,
       1.15479 , 2.203135, 1.53257 , 2.25642 , 2.234425, 1.59192 ,
       2.207165, 3.023045, 1.47084 , 1.84312 , 2.657765, 1.71381 ,
       2.298365, 1.71989 , 2.468225, 1.948545, 1.53998 , 1.69748 ,
       2.49988 , 1.646545, 2.07591 , 2.764245, 1.760995, 2.09178 ,
       1.090995, 2.81613 , 1.869565, 1.503085, 2.28844 , 2.592495,
       1.775745, 0.577485, 2.05532 , 1.879125, 3.05022 , 1.599165,
       2.274575, 1.917445, 1.822625, 1.939555, 1.530185, 2.60403 ,
       0.957005, 1.79361 , 1.48456 , 1.798715, 2.861605, 2.042

In [156]:
y

array([ 2.23863e+00, -1.56000e-03,  3.01665e+00,  2.31019e+00,
        2.05950e+00,  1.24736e+00,  2.82497e+00,  2.21802e+00,
        1.43644e+00,  1.74980e+00,  1.63259e+00,  2.43461e+00,
        1.02226e+00,  3.11769e+00,  8.11940e-01,  2.81910e+00,
        5.31050e-01,  1.64845e+00,  1.91416e+00,  2.11376e+00,
        1.70969e+00,  2.92253e+00,  3.29827e+00,  1.58565e+00,
        2.30455e+00,  1.79169e+00,  1.54723e+00,  1.06893e+00,
        1.78802e+00,  1.84746e+00,  1.58732e+00,  1.94799e+00,
        3.09324e+00,  1.86155e+00,  1.88817e+00,  1.39474e+00,
        1.71526e+00,  1.75695e+00,  1.12981e+00,  1.67000e+00,
        6.67110e-01,  3.11987e+00,  5.69240e-01,  2.28231e+00,
        1.23798e+00,  1.35803e+00,  1.75579e+00,  1.91470e+00,
        2.33029e+00,  3.25263e+00,  2.07602e+00,  1.54254e+00,
        2.79202e+00,  1.96178e+00,  9.58980e-01,  1.96690e+00,
        3.06144e+00,  1.85984e+00,  1.82967e+00,  6.22850e-01,
        3.63838e+00,  1.11807e+00,  2.91735e+00,  1.996

In [157]:
error.sum()

197.26516

In [158]:
k = np.matmul(error, X)

In [159]:
k

array([-21.78649137])

### matmul simple example - multiply array by array with single value

In [200]:

p = np.array([[1],[2],[3],[4],[100]])

k = np.array([1,2,3,4,5])

In [201]:
p.shape

(5, 1)

In [202]:
e = np.array([0.5])

In [203]:
e.shape

(1,)

In [204]:
k.shape

(5,)

In [205]:
np.matmul(p,e)

array([ 0.5,  1. ,  1.5,  2. , 50. ])

In [206]:
np.matmul(k,e)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)