## Single linear regression


In [65]:
from sklearn.linear_model import LinearRegression
model = LinearRegression
import pandas as pd

bmi_life_data = pd.read_csv("bmi_and_life_expectancy.csv")


In [66]:
# Make and fit the linear regression model
#TODO: Fit the model and Assign it to bmi_life_model
bmi_life_model = LinearRegression()
X = bmi_life_data[['BMI']]
y = bmi_life_data['Life expectancy']




In [67]:
y

0      52.8
1      76.8
2      75.5
3      84.6
4      56.7
       ... 
158    63.4
159    74.1
160    74.1
161    51.1
162    47.3
Name: Life expectancy, Length: 163, dtype: float64

In [68]:

bmi_life_model.fit(X,y)


# Make a prediction using the model
# TODO: Predict life expectancy for a BMI value of 21.07931
laos_life_exp = bmi_life_model.predict([[21.07931]])

In [69]:
laos_life_exp

array([60.31564716])

## Multiple linear regression

In [70]:
from sklearn.datasets import load_boston

# Load the data from the boston house-prices dataset 
boston_data = load_boston()

In [74]:
boston_data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [76]:
boston_data['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [83]:
boston_data['DESCR']

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [79]:
X = pd.DataFrame(boston_data.data, columns = boston_data.feature_names)

In [80]:
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [86]:
y = pd.DataFrame(boston_data.target, columns= ['MedValue'])

In [87]:
y

MedValue
0        24.0
1        21.6
2        34.7
3        33.4
4        36.2
..        ...
501      22.4
502      20.6
503      23.9
504      22.0
505      11.9

[506 rows x 1 columns]

In [90]:
model2 = LinearRegression()
model2.fit(X,y)

sample_house = [[2.29690000e-01, 0.00000000e+00, 1.05900000e+01, 0.00000000e+00, 4.89000000e-01,
                6.32600000e+00, 5.25000000e+01, 4.35490000e+00, 4.00000000e+00, 2.77000000e+02,
                1.86000000e+01, 3.94870000e+02, 1.09700000e+01]]
# TODO: Predict housing price for the sample_house
prediction = model2.predict(sample_house)

In [91]:
prediction

array([[23.68284712]])

### Polynomial regression

In [92]:
# TODO: Add import statements
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Assign the data to predictor and outcome variables
# TODO: Load the data
train_data = pd.read_csv('polynom_data.csv')


In [93]:
train_data

Var_X     Var_Y
0  -0.33532   6.66854
1   0.02160   3.86398
2  -1.19438   5.16161
3  -0.65046   8.43823
4  -0.28001   5.57201
5   1.93258 -11.13270
6   1.22620  -5.31226
7   0.74727  -4.63725
8   3.32853   3.80650
9   2.87457  -6.06084
10 -1.48662   7.22328
11  0.37629   2.38887
12  1.43918  -7.13415
13  0.24183   2.00412
14 -2.79140   4.29794
15  1.08176  -5.86553
16  2.81555  -5.20711
17  0.54924  -3.52863
18  2.36449 -10.16202
19 -1.01925   5.31123

In [112]:
X = np.array(train_data[['Var_X']])
y = train_data['Var_Y']


In [113]:
X

array([[-0.33532],
       [ 0.0216 ],
       [-1.19438],
       [-0.65046],
       [-0.28001],
       [ 1.93258],
       [ 1.2262 ],
       [ 0.74727],
       [ 3.32853],
       [ 2.87457],
       [-1.48662],
       [ 0.37629],
       [ 1.43918],
       [ 0.24183],
       [-2.7914 ],
       [ 1.08176],
       [ 2.81555],
       [ 0.54924],
       [ 2.36449],
       [-1.01925]])

In [122]:
# Create polynomial features
# TODO: Create a PolynomialFeatures object, then fit and transform the
# predictor feature
poly_feat = PolynomialFeatures(degree=3)
X_poly = poly_feat.fit_transform(X)

# Make and fit the polynomial regression model
# TODO: Create a LinearRegression object and fit it to the polynomial predictor
# features
poly_model = LinearRegression()
poly_model.fit(X_poly, y)
# Once you've completed all of the steps, select Test Run to see your model
# predictions against the data, or select Submit Answer to check if the degree
# of the polynomial features is the same as ours!

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Regularization with Sklearn

In [146]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso


In [147]:
train_data = pd.read_csv('lasso_regul.csv', header=None)

In [148]:
X = train_data.iloc[:,:-1]
y = train_data.iloc[:,-1]

In [149]:
lasso_reg = Lasso()
lasso_reg.fit(X,y)


#sample check and fit to linear regression as well
lin_reg = LinearRegression()
lin_reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [150]:
reg_coef = lasso_reg.coef_
print(reg_coef)

[ 0.          2.35793224  2.00441646 -0.05511954 -3.92808318  0.        ]


In [151]:
lin_reg_coef = lin_reg.coef_
print(lin_reg_coef)

[-6.19918532e-03  2.96325160e+00  1.98199191e+00 -7.86249920e-02
 -3.95818772e+00  9.30786141e+00]


## Feature scaling

In [160]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler


In [161]:
train_data = pd.read_csv('lasso_regul.csv', header=None)
X = train_data.iloc[:,:-1]
y = train_data.iloc[:,-1]

In [162]:
scaler = StandardScaler()

In [163]:
X_scaled = scaler.fit_transform(X)

In [164]:
lasso_reg2 = Lasso()
lasso_reg2.fit(X_scaled,y)

reg2_coef = lasso_reg2.coef_
print(reg2_coef)

[  0.           3.90753617   9.02575748  -0.         -11.78303187
   0.45340137]


### Checking some descriptive stats of the data used for Lasso/Regularization

In [165]:
train_data.head()

0        1         2        3        4        5         6
0  1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590  12.31798
1 -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640  23.67628
2  5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626  -1.53459
3  0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084 -24.68670
4  5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022  17.54122

In [166]:
train_data.info

<bound method DataFrame.info of            0        1         2        3        4        5         6
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590  12.31798
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640  23.67628
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626  -1.53459
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084 -24.68670
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022  17.54122
..       ...      ...       ...      ...      ...      ...       ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386  26.14768
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617   0.76214
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655 -10.05262
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519 -19.63970
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444  12.76193

[100 rows x 7 columns]>

In [167]:
train_data.describe()

0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean    -0.076288   -0.181381    0.339573    1.772602   -0.168269    0.009754   
std      5.560089    1.737693    4.982072    8.163906    3.184054    0.183237   
min    -12.398240   -5.280250  -11.235910  -23.820240   -6.865330   -0.634440   
25%     -3.880407   -1.222918   -2.833323   -3.383100   -2.731047   -0.099910   
50%     -0.009940   -0.278235   -0.072670    0.711860   -0.120520    0.002385   
75%      4.065705    1.083133    3.855920    6.704855    2.173942    0.119822   
max     13.374540    4.301200   11.946500   22.880080    7.351290    0.523280   

                6  
count  100.000000  
mean     0.744579  
std     17.132932  
min    -45.017100  
25%     -9.455507  
50%      0.415680  
75%     12.878975  
max     36.216980

## reading


https://www.quora.com/Why-do-we-normalize-the-data